'use strict';
const fullName = 'John';
const isCool = true;
const totalPets = 1;
console.log('fullName:', fullName);
console.log('isCool:', isCool);
console.log('totalPets:', totalPets);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
const unknown = null;
console.log('value of unknown:', unknown);
console.log('type of unknown:', typeof unknown);
let never;
console.log('value of never:', never);
console.log('typeof never:', typeof never);
